## Cameron Palmer, 21 May 2020
## Shared pipeline for each platform in turn, pulled in through an include from a dummy makefile controller.
## Note that this means that this is executed from within the {CHIP} directory, and output paths don't include that
## Ancestry is stored in "PROJECT_CODE"
include $(PROJECT_BASE_DIR)/Makefile.config

RESOLVED_SUBJECT_LIST := $(UNIQUE_SUBJECT_LIST)

FILTERED_IMPUTED_DIR := $(FILTERED_IMPUTED_INPUT_DIR)

## input filtered imputed files are only created for platform/ancestry combinations with (by default) at least 100 subjects.
## instead of reconstructing that information from scratch, search the likely directories for dose.vcf.gz files; if they exist,
## that platform/ancestry combination is valid and needs processing
VALID_ANCESTRIES := $(subst /,,$(foreach candidate,$(sort $(dir $(shell find $(FILTERED_IMPUTED_DIR)/$(PROJECT_CODE) -name "*dose.vcf.gz" -print))),$(lastword $(subst $(PROJECT_CODE)/, ,$(candidate)))))

## all targets are: for each autosome, a bgen file, a bgen index (bgi) file, and a sample file with a foolish modification due to software weirdness
ALL_TARGETS := $(foreach ancestry,$(VALID_ANCESTRIES),$(patsubst %,$(ancestry)/chr%-filtered.bgen$(TRACKING_SUCCESS_SUFFIX),$(CHRS)) $(patsubst %,$(ancestry)/chr%-filtered-noNAs.sample$(TRACKING_SUCCESS_SUFFIX),$(CHRS)) $(patsubst %,$(ancestry)/chr%-filtered.bgen.bgi$(TRACKING_SUCCESS_SUFFIX),$(CHRS)))

.DELETE_ON_ERROR:
.SECONDARY:
.SECONDEXPANSION:
.PHONY: all secondary-clean
all: $(ALL_TARGETS)

secondary-clean:
	rm -f $(addsuffix /*.pvar,$(VALID_ANCESTRIES))
	rm -f $(addsuffix /*.psam,$(VALID_ANCESTRIES))
	rm -f $(addsuffix /*-filtered.sample,$(VALID_ANCESTRIES))
	rm -f $(addsuffix /*.pgen,$(VALID_ANCESTRIES))
	rm -f $(addsuffix /*.command.bash,$(VALID_ANCESTRIES))

## patterns:
##    output: {ANCESTRY}/chr{CHR}-filtered-noNAs.sample$(TRACKING_SUCCESS_SUFFIX)
##    input:  {ANCESTRY}/chr{CHR}-filtered.bgen.$(TRACKING_SUCCESS_SUFFIX) (really .sample)
##    input:  {ANCESTRY}/
## Notes: this only exists because plink-format .sample output emits "NA"s when downstream applications expect "0" missing codes.
## .bgen$(TRACKING_SUCCESS_SUFFIX) is the tracker, but the real input is the .sample file.
$(filter %-noNAs.sample$(TRACKING_SUCCESS_SUFFIX),$(ALL_TARGETS)): $$(subst -noNAs.sample,.bgen,$$@) | $$(dir $$@)
	$(call log_handler,$(subst $(TRACKING_SUCCESS_SUFFIX),,$@),sed 's/NA$$/0/' $(subst .bgen$(TRACKING_SUCCESS_SUFFIX),.sample,$<) > $(subst $(TRACKING_SUCCESS_SUFFIX),,$@))

## patterns:
##    output: {ANCESTRY}/chr{CHR}-filtered.bgen$(TRACKING_SUCCESS_SUFFIX)
##    input:  {ANCESTRY}/chr{CHR}-filtered.pgen$(TRACKING_SUCCESS_SUFFIX)
##    input:  {ANCESTRY}.unique.prioritized.keep$(TRACKING_SUCCESS_SUFFIX)
##    input:  {ANCESTRY}/
## Notes: read pgen files with haplotype dosages into plink, emit bgen 1.2 dosages.
$(filter %.bgen$(TRACKING_SUCCESS_SUFFIX),$(ALL_TARGETS)): $$(subst .bgen$(TRACKING_SUCCESS_SUFFIX),.pgen$(TRACKING_SUCCESS_SUFFIX),$$@) $(firstword $(subst /, ,$(PROJECT_CODE))).unique.prioritized.keep$(TRACKING_SUCCESS_SUFFIX) | $$(dir $$@)
	$(call qsub_handler,$(subst $(TRACKING_SUCCESS_SUFFIX),,$@),$(PLINK2) --pfile $(subst .pgen$(TRACKING_SUCCESS_SUFFIX),,$<) --keep $(subst $(TRACKING_SUCCESS_SUFFIX),,$(word 2,$^)) --recode bgen-1.2 bits=8 --out $(subst .bgen$(TRACKING_SUCCESS_SUFFIX),,$@))

## patterns:
##    output: {ANCESTRY}/chr{CHR}-filtered.pgen$(TRACKING_SUCCESS_SUFFIX)
##    input:  {INPUT_FILTERED_DOSAGE_DATA}/{CHIP}/{ANCESTRY}/chr{CHR}-filtered.dose.vcf.gz
##    input:  {ANCESTRY}/
## Notes: read post-imputation-QC by-ancestry data for an autosome, remove the phase (BOLT requirement), write to pgen while saving haplotype dosages
## this has already been handled upstream, but note that this step would remove genotype probabilities. also note that this has to be a separate
## step from the bgen write step because erase-phase is apparently specific to --make-pgen
$(subst .bgen$(TRACKING_SUCCESS_SUFFIX),.pgen$(TRACKING_SUCCESS_SUFFIX),$(filter %.bgen$(TRACKING_SUCCESS_SUFFIX),$(ALL_TARGETS))): $$(FILTERED_IMPUTED_DIR)/$$(PROJECT_CODE)/$$(subst .pgen$(TRACKING_SUCCESS_SUFFIX),.dose.vcf.gz,$$@) | $$(dir $$@)
	$(call qsub_handler,$(subst $(TRACKING_SUCCESS_SUFFIX),,$@),$(PLINK2) --vcf $< dosage=HDS --id-delim _ --make-pgen erase-phase --out $(subst .pgen$(TRACKING_SUCCESS_SUFFIX),,$@))

## patterns:
##    output: {ANCESTRY}/chr{CHR}-filtered.bgen.bgi$(TRACKING_SUCCESS_SUFFIX)
##    input:  {ANCESTRY}/chr{CHR}-filtered.bgen$(TRACKING_SUCCESS_SUFFIX)
## Notes: use bgenix to index the bgen file for use with downstream applications. -clobber required for pipeline reruns.
%.bgi$(TRACKING_SUCCESS_SUFFIX): %$(TRACKING_SUCCESS_SUFFIX)
	$(call qsub_handler,$(subst $(TRACKING_SUCCESS_SUFFIX),,$@),$(BGENIX) -g $(subst $(TRACKING_SUCCESS_SUFFIX),,$<) -index -clobber)

## patterns:
##    output: {ANCESTRY}/
## Notes: if needed, make the ancestry output directory
$(addsuffix /,$(VALID_ANCESTRIES)):
	mkdir -p $@

## patterns:
##    output: {ANCESTRY}.prioritized.keep$(TRACKING_SUCCESS_SUFFIX)
##    input:  {FINAL_NONREDUNDANT_SUBJECT_LIST}
## Notes: this step was previously handled differently, but now there is an apparently canonical list of nonredundant subjects by platform
## created by a collaborator. so in this case, just use that list directly.
%.unique.prioritized.keep$(TRACKING_SUCCESS_SUFFIX): $(RESOLVED_SUBJECT_LIST)
	$(call log_handler,$(subst $(TRACKING_SUCCESS_SUFFIX),,$@),awk -F"\t" '$$NF ~ /$(subst .unique.prioritized.keep$(TRACKING_SUCCESS_SUFFIX),,$@)/ {print $$1"\t"$$1}' $< > $(subst $(TRACKING_SUCCESS_SUFFIX),,$@))

